### ISSUE TITLE
Incompatible with Current Docpad

### ISSUE THREAD

**Issue by jlukic** [almero-digital-marketing/docpad-plugin-copy#4]
I believe Docpad modified how plugins are constructed and it appears this plugin no longer works.

@balupton - Although this isnt an official plugin, it is recommended in [official docs for performance](https://docpad.org/docs/performance)

This was most likely introduced in [`6.82.0`](https://github.com/docpad/docpad/blob/master/HISTORY.md#v6820-2018-september-7)

The release notes read
* The Plugin Loader class has been abstracted out to [pluginloader](https://github.com/bevry/pluginloader) and made generic

Parsed Out JS Issue With Constructor
```javascript
↳ TypeError: Class constructor BasePlugin cannot be invoked without 'new'
    at new Copy (/home/jack/qualia.com/node_modules/docpad-plugin-copy/out/copy.plugin.js:13:43)
```

Full Docpad error

```javascript
 Error: The action [load ready] failed to complete!
    at docpadUtil.action.call.args (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:362:22)
    at TaskGroup.<anonymous> (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/util.js:377:11)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.listener (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.finish (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:131:20)
    at Task.emit (events.js:214:7)
    at Task.listener (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitTwo (events.js:126:13)
    at Task.emit (events.js:214:7)
    at Task.finish (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at TaskGroup.completeMethod (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.listener (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.finish (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at Task.emit (events.js:211:7)
    at Task.listener (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitOne (events.js:116:13)
    at Task.emit (events.js:211:7)
    at Task.finish (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at TaskGroup.<anonymous> (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3298:16)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.listener (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitTwo (events.js:126:13)
    at TaskGroup.emit (events.js:214:7)
    at TaskGroup.finish (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:972:8)
    at TaskGroup.fire (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:1037:10)
    at TaskGroup.itemDoneCallbackNextState (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/taskgroup.js:949:8)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at Task.emit (events.js:211:7)
    at Task.listener (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/interface.js:61:10)
    at emitOne (events.js:116:13)
    at Task.emit (events.js:211:7)
    at Task.finish (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:418:9)
    at Task.itemCompletionCallback (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:375:8)
    at completeMethod (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:507:5)
    at next (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3337:9)
    at DocPad.loadPlugin (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3394:14)
    at Task.<anonymous> (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:242:14)
    at Task.fire (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

↳ Error: Plugin failed to instantiate: /home/jack/qualia.com/node_modules/docpad-plugin-copy
    at DocPad.loadPlugin (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3389:15)
    at Task.<anonymous> (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:242:14)
    at Task.fire (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

↳ Error: Plugin [/home/jack/qualia.com/node_modules/docpad-plugin-copy] failed to instantiate.
    at PluginLoader.create (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:298:10)
    at DocPad.loadPlugin (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3386:51)
    at Task.<anonymous> (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:242:14)
    at Task.fire (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

↳ TypeError: Copy.__super__.constructor.apply is not a constructor
    at new Copy (/home/jack/qualia.com/node_modules/docpad-plugin-copy/out/copy.plugin.js:13:16)
    at PluginLoader.create (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/@bevry/pluginloader/source/index.js:287:19)
    at DocPad.loadPlugin (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3386:51)
    at Task.<anonymous> (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/edition-esnext/lib/docpad.js:3308:25)
    at ambi (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/ambi/source/index.js:77:3)
    at Domain.fireMethod (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:522:5)
    at Domain.run (domain.js:242:14)
    at Task.fire (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:540:15)
    at Immediate.queue (/home/jack/.nvm/versions/node/v8.9.0/lib/node_modules/docpad/node_modules/taskgroup/source/lib/task.js:575:20)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

```

**Comment by balupton** [comment]
Transfer the plugin to the docpad org. And as detailed extensively in the changelog and the issues of the time, it is because the plugin needs to update from coffeescript v1 to v2. The upgrade can be automated by running the boundation package on the plugin. Please refer to the docpad changelog.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by balupton** [comment]
Another bump on this. In the meantime, I've [reverted the docs](https://docpad.bevry.me/start/performance) to recommend the official [docpad-plugin-raw](https://github.com/docpad/docpad-plugin-raw) instead of this third party plugin.

---

Plugin requires updating to CoffeeScript v2. This can be done automatically via running [boundation](https://github.com/bevry/boundation) on it. If you would like the DocPad team to do it, then:

1. transfer the repo to the https://github.com/docpad organisation
2. then run the following:
    - `npm owner add balupton docpad-plugin-copy`
    - `npm owner add bevryme docpad-plugin-copy`

If these actions are performed on [all your DocPad plugins](https://github.com/almero-digital-marketing?q=docpad&type=&language=) then the community can take over maintenance for all of them.

All copyright and all associated klout will be retained.

**Comment by balupton** [comment]
Sent Almero an email to follow up.

**Comment by balupton** [comment]
I'll give it until next week, if still nothing, we'll just fork the repos and release them under @docpad/docpad-plugin-
